#Lets start with numpy   ............our journey of DATA SCI proceeds now !!

In [2]:
import numpy as np

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

In [5]:
n = np.array((1,2,3,4,5))
print(n)

[1 2 3 4 5]


In [6]:
print(type(n))

<class 'numpy.ndarray'>


In [8]:
# Basics

In [13]:
m = np.array([[9.1,7,8,9.9],[4.0,7.0,6.9]])
m

C:\Users\Keval Shah\AppData\Local\Temp\ipykernel_2636\1682693368.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  m = np.array([[9.1,7,8,9.9],[4.0,7.0,6.9]])


array([list([9.1, 7, 8, 9.9]), list([4.0, 7.0, 6.9])], dtype=object)

In [14]:
import numpy as np

data = [[9.1, 7, 8, 9.9], [4.0, 7.0, 6.9]]
m = np.array(data, dtype=object)

print(m)


[list([9.1, 7, 8, 9.9]) list([4.0, 7.0, 6.9])]


In [16]:
#Get Dimension
m.ndim

1

In [17]:
#Get Type
a.dtype

NameError: name 'a' is not defined

In [2]:
n.itemsize

NameError: name 'n' is not defined

In [3]:
import numpy as np

data = [[9.1, 7, 8, 9.9], [4.0, 7.0, 6.9]]
m = np.array(data, dtype=object)
m.itemsize

8

In [4]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [6]:
a.shape

(2, 7)

In [7]:
# To get a spwcific element a[row,column]
a[0,4]

5

In [8]:
a[1,3]

11

In [9]:
# To get a specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [10]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
#a[start_index,stop_index,step_size]
a[0,1:7:2]

array([2, 4, 6])

In [13]:
# To get a specific column
a[:,1]

array([2, 9])

In [14]:
a[::-1,0]

array([8, 1])

In [16]:
# To reverse everything
a[::-1,::-1]

array([[14, 13, 12, 11, 10,  9,  8],
       [ 7,  6,  5,  4,  3,  2,  1]])

In [6]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a[1,5] = 20

a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [9]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
# To get a specific element (work outside in)
b[0,1,1]

4

In [12]:
b[1,0,1]

6

In [16]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [19]:
# Replace
b[0,1,1] = 10
print(b)


[[[ 1  2]
  [ 3 10]]

 [[ 5  6]
  [ 7  8]]]


In [20]:
# Initializing different types of arrays


In [24]:
# All 0s matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# All 1s matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
# All 1s matrix
np.ones((2,3),dtype ='int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [27]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [28]:
np.full((3,3),101)

array([[101, 101, 101],
       [101, 101, 101],
       [101, 101, 101]])

In [29]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [30]:
# Random decimal numbers
np.random.rand(4,5)

array([[0.22193033, 0.00335539, 0.04085796, 0.80759663, 0.54664454],
       [0.8580745 , 0.47915356, 0.5762548 , 0.70716932, 0.48366363],
       [0.56816764, 0.09671782, 0.80356532, 0.80907474, 0.83194177],
       [0.4797703 , 0.27677995, 0.98529799, 0.00708687, 0.86281822]])

In [32]:
# Random integer values
np.random.randint(-4,8,size=(3,3))

array([[ 1,  0,  5],
       [ 5,  4,  6],
       [ 5, -1, -4]])

In [33]:
# Get Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# To repeat an array
arr = np.array([[1,2,3]])
r = np.repeat(arr,3,axis = 0)
r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [39]:
# To repeat an array
arr = np.array([[1,2,3]])
r = np.repeat(arr,3,axis = 1)
r

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [40]:
# Copying Arrays
a = np.array([[1,2,3,4,5]])
b = a.copy()
b

array([[1, 2, 3, 4, 5]])

In [48]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output
z
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [49]:
## Mathematics 
a = np.array([[1,2,3]])

In [50]:
a+1

array([[2, 3, 4]])

In [51]:
a-1

array([[0, 1, 2]])

In [52]:
a*2

array([[2, 4, 6]])

In [53]:
a/2

array([[0.5, 1. , 1.5]])

In [54]:
a%2

array([[1, 0, 1]], dtype=int32)

In [55]:
b = np.array([[1,0,1,0]])

In [56]:
a+b

ValueError: operands could not be broadcast together with shapes (1,3) (1,4) 

In [57]:
a = np.array([[1,2,3,4]])


In [58]:
a+b

array([[2, 2, 4, 4]])

In [59]:
a-b

array([[0, 2, 2, 4]])

In [60]:
a*b

array([[1, 0, 3, 0]])

In [61]:
a/b

C:\Users\Keval Shah\AppData\Local\Temp\ipykernel_16676\1348051284.py:1: RuntimeWarning: divide by zero encountered in divide
  a/b


array([[ 1., inf,  3., inf]])

In [62]:
# lets do some trigo

a = np.array([[30,60,90]])

In [64]:
np.sin(a)

array([[-0.98803162, -0.30481062,  0.89399666]])

In [65]:
np.sin(np.pi/2)

1.0

In [66]:
a = np.ones((2,4))

In [67]:
b = np.full((4,2),3)

In [69]:
c = np.matmul(a,b)
c

array([[12., 12.],
       [12., 12.]])

In [70]:
d = np.matmul(b,a)
d

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [71]:
# to find determinant
e = np.identity((3))

In [74]:
f = np.linalg.det(e)
f

1.0

In [75]:
# Statistics


In [76]:
a = np.array([[1,2,3],[4,5,6]])

In [77]:
np.min(a)

1

In [78]:
np.mean(a)

3.5

In [84]:
np.median(a)

3.5

In [85]:
## Recorganizing arrays



In [86]:
before = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(before)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [93]:
after = before.reshape((5,2))
print(after)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [2]:
import numpy as np

In [4]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

FileNotFoundError: data.txt not found.

In [27]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [9]:
sample_array = np.array([[1,2,3],[4,5,6]])
specified_array = np.array([1,2,3])
row_exists = np.any(np.all(sample_array == specified_array,axis=1))

if row_exists:
    print('It exists')
else:
    print('It doesnt exists')

It exists


In [10]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[4,5],[6,7]])

add_mat = np.add(mat1,mat2)
add_mat

array([[ 5,  7],
       [ 9, 11]])

In [11]:
mul_mat = np.matmul(mat1,mat2)
mul_mat

array([[16, 19],
       [36, 43]])

In [17]:
x = np.array([1, 2, 4, 3, 2, 4, 2, 5, 6, 3, 3, 2, 4, 2, 4, 1])

unique_values, counts = np.unique(x, return_counts=True)
max_count_index = np.argmax(counts)

most_frequent_value = unique_values[max_count_index]
most_frequent_count = counts[max_count_index]

print(f"The most frequent value is: {most_frequent_value}")
print(f"It appears {most_frequent_count} times.")

The most frequent value is: 2
It appears 5 times.


In [19]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr_1d_flatten = arr_2d.flatten()

print("Flatten :", arr_1d_flatten)

Flatten : [1 2 3 4 5 6 7 8 9]


In [20]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
column_sums = np.sum(array_2d, axis=0)
print("Sum of each column:")
print(column_sums)

Sum of each column:
[12 15 18]


In [22]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 34, 45])
average = np.mean(data)
variance = np.var(data)
std_dev = np.std(data)
print("Average:", average)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Average: 9.785714285714286
Variance: 159.31122448979593
Standard Deviation: 12.621855033623067


In [3]:
array = np.array(["Vivek", "rizz", "Nair"])
array_with_space = np.array([" ".join(list(word)) for word in array])
print(array_with_space)

['V i v e k' 'r i z z' 'N a i r']


In [26]:
matrix = np.array([[3, 2, 1], [6, 5, 4], [9, 8, 7]])
sorted_matrix = np.sort(matrix)
print("Sorted Matrix:")
print(sorted_matrix)

Sorted Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [1]:
import numpy as np

In [3]:
print(np.reshape(list(map(int,input().split())),(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
n,m = map(int,input().split())

2 3


In [9]:
import numpy as np
N,M = map(int,input().split())
arr = np.array([list(map(int,input().split())) for _ in range(N)])
print(np.transpose(arr))
print(arr.flatten())

1 3
1 2 3 4 5 6
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]


In [12]:
import numpy

array_1 = numpy.array([[1,2,3],[0,0,0]])
array_2 = numpy.array([[0,0,0],[7,8,9]])

print (numpy.concatenate((array_1, array_2), axis = 1))   

#Output
# [[1 2 3 0 0 0]
#  [0 0 0 7 8 9]]

[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]


Input Format

The first line contains space separated integers ,  and .
The next  lines contains the space separated elements of the  columns.
After that, the next  lines contains the space separated elements of the  columns.

Output Format

In [13]:
N,M,P = map(int,input().split())

2 3 4


In [14]:
m1 = np.array([list(map(int,input().split())) for _ in range(N)])
m2 = np.array([list(map(int,input().split())) for _ in range(M)])
seq = (m1,m2)
print(np.concatenate(seq,axis=0))

1 2 3 4 
5 6 7 8
1 2 3 4
5 6 7 8
9 8 7 6
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]]
